version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: saynotodream
      POSTGRES_PASSWORD: 0p3nw0rld
      POSTGRES_DB: postgres
    ports:
      - "2345:5432"
    volumes:
      - ./data:/var/lib/postgres
    networks:
      - network-postgres
      
networks:
  network-postgres:
    driver: bridge
    name: network-postgres
     
